name: Build CMake for Android (All Architectures)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86_64, x86]

    steps:
    - name: Checkout CMake Source
      uses: actions/checkout@v4
      with:
        repository: Kitware/CMake
        ref: master
        path: CMake

    - name: Setup NDK r29
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r29
        add-to-path: true

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake python3 build-essential

    - name: Apply Android Patches
      run: |
        cd CMake
        
        echo "=== Patching libuv for Android API 21 ==="
        
        # Fix uv_cpumask_size - line 1410
        sed -i '1410s/#if defined(__linux__) || defined(__FreeBSD__)/#if (defined(__linux__) \&\& (!defined(__ANDROID__) || __ANDROID_API__ >= 28)) || defined(__FreeBSD__)/' \
          Utilities/cmlibuv/src/unix/core.c
        
        # Fix uv_available_parallelism - line 1647
        sed -i '1647s/#ifdef __linux__/#if defined(__linux__) \&\& (!defined(__ANDROID__) || __ANDROID_API__ >= 28)/' \
          Utilities/cmlibuv/src/unix/core.c
        
        # Fix pipe2 for Android API 21 - add fallback at top of file
        sed -i '/^#include "uv.h"/a \
        \
        /* Android API 21 pipe2 fallback */ \
        #if defined(__ANDROID__) \&\& __ANDROID_API__ < 21 \
        #include <fcntl.h> \
        static int pipe2(int pipefd[2], int flags) { \
          int ret = pipe(pipefd); \
          if (ret == 0) { \
            if (flags \& O_CLOEXEC) { \
              fcntl(pipefd[0], F_SETFD, FD_CLOEXEC); \
              fcntl(pipefd[1], F_SETFD, FD_CLOEXEC); \
            } \
            if (flags \& O_NONBLOCK) { \
              fcntl(pipefd[0], F_SETFL, O_NONBLOCK); \
              fcntl(pipefd[1], F_SETFL, O_NONBLOCK); \
            } \
          } \
          return ret; \
        } \
        #endif' Utilities/cmlibuv/src/unix/pipe.c
        
        echo "=== Creating android_lf.h ==="
        cat > Utilities/cmlibarchive/libarchive/android_lf.h << 'EOF'
        #ifndef ANDROID_LF_H
        #define ANDROID_LF_H
        
        #include <sys/types.h>
        #include <fcntl.h>
        #include <unistd.h>
        #include <sys/stat.h>
        
        #if defined(__ANDROID__)
        #ifndef lstat64
        #define lstat64 lstat
        #endif
        #ifndef stat64
        #define stat64 stat
        #endif
        #ifndef fstat64
        #define fstat64 fstat
        #endif
        #ifndef open64
        #define open64 open
        #endif
        #ifndef lseek64
        #define lseek64 lseek
        #endif
        #ifndef off64_t
        #define off64_t off_t
        #endif
        #ifndef ftruncate64
        #define ftruncate64 ftruncate
        #endif
        #ifndef readdir64
        #define readdir64 readdir
        #endif
        #ifndef dirent64
        #define dirent64 dirent
        #endif
        #endif
        
        #endif
        EOF
        
        echo "=== Patches applied ==="
        echo "Verifying pipe.c patch:"
        head -30 Utilities/cmlibuv/src/unix/pipe.c | grep -A5 "pipe2"

    - name: Build Native CMake (Host Tools)
      run: |
        cd CMake
        mkdir -p build-host
        cd build-host
        
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=OFF \
          -DBUILD_QtDialog=OFF \
          -DCMAKE_USE_SYSTEM_LIBRARIES=OFF
        
        make -j$(nproc)
        
        echo "=== Host cmake built ==="
        ./bin/cmake --version

    - name: Configure Android Build
      run: |
        cd CMake
        
        case "${{ matrix.arch }}" in
          arm64-v8a)
            ANDROID_ABI="arm64-v8a"
            CLANG_PREFIX="aarch64-linux-android"
            ;;
          armeabi-v7a)
            ANDROID_ABI="armeabi-v7a"
            CLANG_PREFIX="armv7a-linux-androideabi"
            ;;
          x86_64)
            ANDROID_ABI="x86_64"
            CLANG_PREFIX="x86_64-linux-android"
            ;;
          x86)
            ANDROID_ABI="x86"
            CLANG_PREFIX="i686-linux-android"
            ;;
        esac
        
        echo "ANDROID_ABI=$ANDROID_ABI" >> $GITHUB_ENV
        echo "CLANG_PREFIX=$CLANG_PREFIX" >> $GITHUB_ENV
        
        mkdir -p build-android-${{ matrix.arch }}
        cd build-android-${{ matrix.arch }}
        
        ../build-host/bin/cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ANDROID_ABI \
          -DANDROID_PLATFORM=android-21 \
          -DANDROID_NDK=$ANDROID_NDK_HOME \
          -DCMAKE_SYSTEM_NAME=Android \
          -DCMAKE_BUILD_TYPE=MinSizeRel \
          -DCMAKE_C_FLAGS="-Os -ffunction-sections -fdata-sections -fvisibility=hidden" \
          -DCMAKE_CXX_FLAGS="-Os -ffunction-sections -fdata-sections -fvisibility=hidden -fno-rtti" \
          -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--gc-sections -Wl,--strip-all -Wl,-z,max-page-size=16384" \
          -DBUILD_TESTING=OFF \
          -DBUILD_QtDialog=OFF \
          -DCMAKE_USE_SYSTEM_LIBRARIES=OFF

    - name: Build CMake for Android
      run: |
        cd CMake/build-android-${{ matrix.arch }}
        
        echo "=== Building CMake for ${{ matrix.arch }} ==="
        make -j$(nproc)
        
        if [ ! -f lib/libCMakeLib.a ]; then
          echo "ERROR: libCMakeLib.a not built!"
          exit 1
        fi
        
        echo "=== Build completed ==="
        ls -lh lib/libCMakeLib.a

    - name: Create Shared Library
      run: |
        cd CMake/build-android-${{ matrix.arch }}
        
        CLANG_BIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
        
        echo "=== Creating libcmake.so ==="
        ${CLANG_BIN}/${{ env.CLANG_PREFIX }}21-clang++ \
          -shared -o libcmake.so \
          -Wl,--whole-archive lib/libCMakeLib.a -Wl,--no-whole-archive \
          -Os -ffunction-sections -fdata-sections \
          -Wl,--gc-sections -Wl,--strip-all -Wl,-z,max-page-size=16384 \
          -Wl,--export-dynamic \
          -fPIC -ldl -llog -latomic
        
        ${CLANG_BIN}/llvm-strip --strip-unneeded libcmake.so
        
        ls -lh libcmake.so
        file libcmake.so

    - name: Package Build
      run: |
        cd CMake/build-android-${{ matrix.arch }}
        
        mkdir -p package/lib
        cp libcmake.so package/lib/
        
        cat > package/README.md << EOF
        # CMake Android Library - ${{ matrix.arch }}
        
        Architecture: ${{ matrix.arch }}
        Target: ${{ env.CLANG_PREFIX }}
        Min API: 21 (Android 5.0+)
        NDK: r29
        
        Size: $(du -h libcmake.so | cut -f1)
        EOF
        
        tar -czf cmake-android-${{ matrix.arch }}.tar.gz -C package .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cmake-android-${{ matrix.arch }}
        path: CMake/build-android-${{ matrix.arch }}/cmake-android-${{ matrix.arch }}.tar.gz
        retention-days: 30

    - name: Build Summary
      run: |
        cd CMake/build-android-${{ matrix.arch }}
        
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "  CMake Android: ${{ matrix.arch }}"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "Size: $(ls -lh libcmake.so | awk '{print $5}')"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
